# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('time', models.TimeField(verbose_name='create time')),
                ('source', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_post_num', models.IntegerField(default=0)),
            ],
        ),
    ]
