# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(max_length=1000),
        ),
    ]
