# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20160710_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_link',
            field=models.TextField(default='www.default.com'),
            preserve_default=False,
        ),
    ]
