# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20160709_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name='Post Create Time'),
        ),
    ]
