# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('create_time', models.DateTimeField(verbose_name='Post Create Time')),
                ('source', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
    ]
