# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_auto_20160709_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='fuck',
            field=models.CharField(default='fuck', max_length=100),
        ),
    ]
